### ISSUE TITLE
Please provide an example of using plain html document and unpkg.com as source

### ISSUE THREAD

**Issue by MarcSkovMadsen** [DoubleTrade/lit-datatable#16]
I'm trying this out in a Jupyter Notebook where I can use plain css, html and js and resources from CDNs like unpkg.com because I eventually want to contribute this an example of using a web component with [Panel](https://panel.holoviz.org/).

It works for me with a lot of other web components like the material `mwc` components, `perspective-viewer`, `wired` widgets etc.

But I cannot get it working for `lit-datatable`. If possible please provide a working example in a plain .html document. 

Thanks.

#### Screenshot

![image](https://user-images.githubusercontent.com/42288570/79627164-5efbd180-8136-11ea-86d0-8c07846f177e.png)

#### Code

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Experiment</title>
    <script type="module" src="https://unpkg.com/@doubletrade/lit-datatable@0.3.5/lit-datatable.js?module"></script>
  </head>
  <body>
    <lit-datatable
        .data="[{ fruit: 'apple', color: 'green', weight: '100gr' },{ fruit: 'banana', color: 'yellow', weight: '140gr' }]"
        .conf="[{ property: 'fruit', header: 'Fruit', hidden: false },{ property: 'color', header: 'Color', hidden: true },{ property: 'weight', header: 'Weight', hidden: false }]"
    ></lit-datatable>
  </body>
</html>
```

**Comment by MarcSkovMadsen** [comment]
I actually got this working. But still it might be a good idea to provide a simple `.html` example for others.

![image](https://user-images.githubusercontent.com/42288570/79627423-4d1b2e00-8138-11ea-8ac6-69ce760ea95d.png)


```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Experiment</title>
    <script type="module" src="https://unpkg.com/@doubletrade/lit-datatable@0.3.5/lit-datatable.js?module"></script>
  </head>
  <body>
    <lit-datatable
        data='[{"fruit": "apple"}]'
        conf='[{"property": "fruit","header":"Fruit","hidden":false}]'
    ></lit-datatable>
  </body>
</html>
```

**Comment by RoXuS** [comment]
More info in https://github.com/DoubleTrade/lit-datatable/issues/22
