### ISSUE TITLE
Pinned dependencies causes duplicate modules

### ISSUE THREAD

**Issue by tpluscode** [DoubleTrade/lit-datatable#18]
This error is thrown when I import `lit-datatable-column`

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
```

This is because the package depends on a specific (`3.2.0`) version of polymer but other packages install newer versions and this results in multiple copies of Polymer in node_modules

**Comment by tpluscode** [comment]
Same goes for `lit-html` actually

**Comment by RoXuS** [comment]
Hey, can you try on master now?

**Comment by RoXuS** [comment]
do you still have this issue?

**Comment by tpluscode** [comment]
Hey, sorry, I eventually ended up using a different element 😬 .

**Comment by RoXuS** [comment]
Np :D
