### ISSUE TITLE
Feature: editing data

### ISSUE THREAD

**Issue by nandoflorestan** [DoubleTrade/lit-datatable#23]
Do we intend to add editing of rows in the future, or will this be for presenting data only?

Is there a roadmap?

Any chance of replacing GPL 3.0 with a more open license?  I ask because I believe if I use this component in a commercial application, I might have to publish the source code for the entire application.  I would recommend MIT license for this sort of thing...

**Comment by RoXuS** [comment]
I have updated the license.

To edit, you can already do it by using renderer.
Something like this:

````
        <lit-datatable .data="${data}" .conf="${conf}">
          <lit-datatable-column column property="fruit" .html="${bodyOfFruit}"></lit-datatable-column>
        </lit-datatable>
...
    const bodyOfFruit = (value, property) => html`<input .value="${value}" .label="${property}" />`;
````

You can use more complexe html with:

````
    const bodyOfFruit = (value, property) => html`
     ${this.editMode ? html`
       <input .value="${value}" .label="${property}" />` : `<div>${value}</div>`}
    `;

````

**Comment by nandoflorestan** [comment]
Thank you very much for changing the license!

You changed it to Apache 2.0 which unfortunately is one of those pain-in-the-ass licenses that pollute code files with legalese.  See item 4b in it, for instance.  But it is better for this component than GPL 3.0...

I am curious, why was MIT license too big of a jump for you?
